language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: 5+siTVjUQF9Cx9Ci0u5RzvKelUvwZxh7DnH1M37O6OsPa9FLYDYsafTx3YspY3sOHaw9b8//My+QF8BZBd5fj+xOruymPRykv0H7ns1xBYoTxBttp/juojgo3fVlTvJtymYFZFyMN2Mi3+AR4vHrb4n3rz/srC6f7aAoOdHGayrX9Uun9dSpmFfDnu0QMNR1n2hDTepBk4rqw6lU8mPqdx6Fc/hZR1miV301uoAeCQvEdNAD3nP2kD331ovoFkbYNwypFCoSYicAYIUAgJ3a5g0q+NjwpItNEDhHESl67uoO2zwCXX/olOGBxjM8FAwMIMQJDSPqEDIqPPjCKbG9tJEr/JDbqTEdddk41NUEN2xytGsLEawmSUz04BumOCA+/dLeIz76r8N4W8ljPV1y9r5scz3dMTCrvuxEkxSc8+sV6MOizRezwy/OqcqnaR1OwLiqySIG8pNC1yQm1p5OphVeTS4/QKyfXuuzeFZdnrEuwaUKkqwpL2hHR4A4l5zrlB1ZC4/ciaaBNM+RIuDLb8BLBv4h7UCtqKMQ1ESpZKGZh0dVsqMYfQ9SmH5CaZjnrpUyW7y77tRl+ATGioTUuPXFpM3itrJMKgOMC04DnDT0UK/Y2q8i3Y6uTCHAmrp7hD55GJMvuMpmKovDaP0088R1FyCcuD/XvP0Av+yKIz4=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: s57GdxVk3m9/bFo9GNnajz7XpNc7feJc4BNmQleRY1hnBEk7eUrUYwnswBS4nIDCjhoj6NNr8uHHxj9ljr9ttawbBbJFnhNsp7V5gQLqHg36wmN/nm6BLJ9RukXzBbTlz7lE8eo7KBkGJ5pc5wx9pM2ma6H/R9zdEmkCFfNMt1yJVpQ+Hd1tabOOYK8LtaedGYVIvuwJxb2RQ2igOaEvU4SjKUvua7lL/2d4wMaqWDVs3bdSOGDs0ErydYHEADmCsZVoC43vxKDo4FrVBo1yIPZFcLFq9+pVhFFH7c2qO9k5/pK2S+agWj2/ACQ2kPo/COdMNxHb27W9A5tBaiika+5ubTlmDcfjhg3J4slUTj3+XfKEAvE9I6tv2SDYFQe3j1OX5b0cyKPpRPYTt3cMtTRg5lZ4au/cos6NWygNdhb/a4IBjh9ayBVj24BfGkh03Xgsq2TUfZ6ZxBJTGSVLTtksKh50yYAS28OM3ZE0LpgT7sLquKX5TfWVmHZFROclfI+ePcKzDiu2Sm/5t6Hwg/S2yo1F4vdQfOY9XUNHOLHFj6MyBZnNrHE8Gq8sdMoOcN6J3ftVw8q2FTJSaEak79FAZ7+hldB08Xb7Kedvx0H53ItxXo6VuQ/j5wpgP634t+CJ+nYbo8jIxb7AZf+HQ9zpHLEAYdxIoumXnad6sJk=
    on_success: change
    on_failure: always
